import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { extractPdfPages } from "../pdf.js";
import { ScanResult } from "../schemas.js";

export interface CutOptions {
  pdf: string;
  scan: string;
  out: string;
  /**
   * Escape hatch: operator-supplied extra ranges, format "Title:from-to".
   * NOT used in the default flow — the scan stage sees every page itself
   * (DECISIONS.md D11). Kept for debugging/comparison runs only.
   */
  extra: string[];
}

function parseExtra(spec: string): { title: string; from: number; to: number } {
  const m = /^(.+):(\d+)-(\d+)$/.exec(spec);
  if (!m) throw new Error(`--extra expects "Title:from-to", got: ${spec}`);
  return { title: m[1]!, from: Number(m[2]), to: Number(m[3]) };
}

/**
 * Stage 2 — `cut`: deterministic page slicing. No LLM. Takes the page ranges
 * the scan marked relevant and writes them to a single readable markdown file.
 * Committed as data/subset.md so reviewers can read exactly what the extractor
 * saw — the audit seam that let us root-cause the round-1 recall miss.
 */
export async function runCut(opts: CutOptions): Promise<void> {
  const scan = ScanResult.parse(JSON.parse(await readFile(opts.scan, "utf8")));
  const { totalPages, pages } = await extractPdfPages(opts.pdf);

  type Range = { title: string; from: number; to: number; provenance: "scan" | "operator" };
  const ranges: Range[] = scan.ranges.map((r) => ({
    title: r.from === r.to ? `Scanned page ${r.from}` : `Scanned pages ${r.from}–${r.to}`,
    from: r.from,
    to: r.to,
    provenance: "scan",
  }));
  for (const spec of opts.extra) {
    const e = parseExtra(spec);
    ranges.push({ title: e.title, from: e.from, to: e.to, provenance: "operator" });
  }
  if (ranges.length === 0) throw new Error("scan contains no relevant ranges — nothing to cut");

  const reasonByPage = new Map(scan.relevant_pages.map((p) => [p.page, p.reason]));

  const parts: string[] = [
    `# Extraction subset`,
    "",
    "> Generated by `npm run cut` from the scan's relevant pages. Deterministic — no LLM.",
    `> Scan coverage: all ${scan.total_pages} pages classified; ${scan.relevant_pages.length} marked relevant.`,
    "",
  ];

  for (const s of ranges) {
    const end = Math.min(s.to, totalPages);
    const body = pages
      .slice(s.from - 1, end)
      .map((t, i) => {
        const p = s.from + i;
        const reason = reasonByPage.get(p);
        return `[PDF p.${p}]${reason ? ` <!-- scan: ${reason} -->` : ""}\n${t.trim()}`;
      })
      .join("\n\n");
    const tag = s.provenance === "operator" ? " — operator-added range" : "";
    parts.push(`\n## ${s.title}${tag}\n`, body);
  }

  const subset = parts.join("\n");
  await mkdir(dirname(opts.out), { recursive: true });
  await writeFile(opts.out, subset + "\n");

  const words = subset.split(/\s+/).length;
  console.error(`cut: ${ranges.length} ranges → ${opts.out} (~${words} words)`);
}
