import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { extractPdfPages } from "../pdf.js";
import { ExtractionPlan } from "../schemas.js";

export interface CutOptions {
  pdf: string;
  plan: string;
  out: string;
  /**
   * Operator-supplied extra ranges the TOC cannot reveal (e.g. a rule section
   * buried inside a legal-instrument appendix), format: "Title:from-to".
   * Kept explicit on the CLI so the subset provenance stays honest — the
   * planner never pretends to have found these. See DECISIONS.md.
   */
  extra: string[];
}

function parseExtra(spec: string): { title: string; from: number; to: number } {
  const m = /^(.+):(\d+)-(\d+)$/.exec(spec);
  if (!m) throw new Error(`--extra expects "Title:from-to", got: ${spec}`);
  return { title: m[1]!, from: Number(m[2]), to: Number(m[3]) };
}

/**
 * Stage 2 — `cut`: deterministic page slicing. No LLM. Takes the sections the
 * planner marked relevant and writes them to a single readable markdown file,
 * one section per heading. Committed as data/subset.md so reviewers can read
 * exactly what the extractor saw.
 */
export async function runCut(opts: CutOptions): Promise<void> {
  const plan = ExtractionPlan.parse(JSON.parse(await readFile(opts.plan, "utf8")));
  const { totalPages, pages } = await extractPdfPages(opts.pdf);

  type Range = { title: string; from: number; to: number; provenance: "planner" | "operator" };
  const relevant: Range[] = plan.sections.filter((s) => s.relevant).map((s) => ({
    title: s.title,
    from: s.start_page,
    to: s.end_page,
    provenance: "planner",
  }));
  for (const spec of opts.extra) {
    const e = parseExtra(spec);
    relevant.push({ title: e.title, from: e.from, to: e.to, provenance: "operator" });
  }
  if (relevant.length === 0) throw new Error("plan contains no relevant sections — nothing to cut");

  const parts: string[] = [
    `# ${plan.document_title} — extraction subset`,
    "",
    "> Generated by `npm run cut` from the planner's relevant sections. Deterministic — no LLM.",
    "",
  ];

  for (const s of relevant) {
    const end = Math.min(s.to, totalPages);
    const body = pages
      .slice(s.from - 1, end)
      .map((t, i) => `[PDF p.${s.from + i}]\n${t.trim()}`)
      .join("\n\n");
    const tag = s.provenance === "operator" ? " — operator-added range" : "";
    parts.push(`\n## ${s.title}  (PDF p.${s.from}–${end}${tag})\n`, body);
  }

  const subset = parts.join("\n");
  await mkdir(dirname(opts.out), { recursive: true });
  await writeFile(opts.out, subset + "\n");

  const words = subset.split(/\s+/).length;
  console.error(`cut: ${relevant.length} sections → ${opts.out} (~${words} words)`);
}
